name: 'breastfeeding_analytics'
version: '1.0.0'
config-version: 2

profile: 'breastfeeding_analytics'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  breastfeeding_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
